name: Docker build & push

on:
  # push:
  #   branches:
  #     - 'github-action-docker-build-push'
  create:
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
       name: Docker meta
       id: meta
       uses: docker/metadata-action@v3
       with:
         images: b3f3/private
         tags: |
           type=ref,event=tag
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
         labels: |
           org.opencontainers.image.title=Hello-World
           org.opencontainers.image.description=This your first repo!
           org.opencontainers.image.url=https://github.com/benjamin-feron/sandbox
           org.opencontainers.image.source=https://github.com/benjamin-feron/sandbox
           org.opencontainers.image.licenses=MIT
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          #platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
