name: Test code

on: [push]

jobs:
  one-host-default-port-no-port-forward:
    runs-on: ubuntu-latest

    container:
      image:  kroniak/ssh-client:latest

    services:
      host-1:
        image: linuxserver/openssh-server
        #ports:
        #- 6379:6379
        #options: --entrypoint redis-server
        env:
          USER_NAME=test
          USER_PASSWORD=test

    steps:
    - uses: actions/checkout@v1

    - run: ssh -T test:test@host-1
    #  working-directory: ./redis

    #- run: node client.js
    #  working-directory: ./redis
    #  env:
    #    REDIS_HOST: redis
    #    REDIS_PORT: ${{ job.services.redis.ports[6379] }}
