name: Test code

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - dev

jobs:
  one-host-default-port-no-port-forward:
    runs-on: ubuntu-latest

    container:
      image:  alpine:latest

    services:
      host-1:
        image: linuxserver/openssh-server
        #ports:
        #- 6379:6379
        #options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - run: ssh host-1
    #  working-directory: ./redis

    #- run: node client.js
    #  working-directory: ./redis
    #  env:
    #    REDIS_HOST: redis
    #    REDIS_PORT: ${{ job.services.redis.ports[6379] }}
